export enum Region {
    ChanghuaCounty = "CHA",
    ChiayiCounty = "CYQ",
    HsinchuCounty = "HSQ",
    HualienCounty = "HUA",
    YilanCounty = "ILA",
    KinmenCounty = "KIN",
    LienchiangCounty = "LIE",
    MiaoliCounty = "MIA",
    NantouCounty = "NAN",
    PenghuCounty = "PEN",
    PingtungCounty = "PIF",
    TaitungCounty = "TTT",
    YunlinCounty = "YUN",
    ChiayiCity = "CYI",
    HsinchuCity = "HSZ",
    KeelungCity = "KEE",
    KaohsiungCity = "KHH",
    NewTaipeiCity = "NWT",
    TaoyuanCity = "TAO",
    TainanCity = "TNN",
    TaipeiCity = "TPE",
    TaichungCity = "TXG",
}
